# This file contains responses for inline mode
# You can use it to define responses for inline queries

[pair]
id = "01"
emoji = ["❤️", "💕", "💜", "💙", "💖", "💗", "🏳️‍🌈", "🏳️‍⚧️"]
title = "Наскільки ви підходите один одному?"
title_with_name = "Наскільки ви з {name} підходите один одному?"
response = "Ви з {name} підходите один одному на {emoji} {percent}% {emoji}"
username_response = "{emoji} Ви з {name} підходите один одному на {percent}% {emoji}"
description = "Обирай собі пару"
img_url = "https://i.imgflip.com/4oqd5v.jpg?a477696"

[dck]
id = "02"
title = "Якого розміру в тебе пісюн?"
emoji = ["🌶️", "🥕", "🍆", "🍌", "🥖", "🌭"]
missing_response = "У тебе немає члена 🌚"
smallest_response = "👆 Найменший член в групі"
normal_response = "{emoji} Твій пісюн - {len}см"
largest_response = "🔥 Найбільший член в групі 🔥"
description = "Роздівайся"
img_url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCr6MmVDOTyOxj9OH8iUBZOB78-1InmDBBFg&s"

[polyana]
id = "03"
title = "Чи йти тобі на поляну?"
responses = [
  "Так",
  "Звичайно",
  "Авжеж",
  "Само собою",
  "Безперечно",
  "Аякже",
  "Ну звісно",
  "Так-так-так",
  "Сто відсотків",
  "👍",
]
description = "Шара тебе чекає"
img_url = "https://tut-kiev.com/wp-content/uploads/2018/06/20180526_134658.jpg"

[gender]
id = "04"
title = "Який у тебе гендер?"
responses = [
  "Чоловік",
  "Жінка",
  "Небінарний",
  "Агендер",
  "Бігендер",
  "Гендерквір",
  "Гендерфлюїд",
  "Демігендер",
  "Панггендер",
  "Трансчоловік",
  "Трансжінка",
  "Трансгендер",
  "Квір",
  "Дводуховий (Two-Spirit)",
  "Інтерсекс",
  "Полігендер",
  "Третя стать",
  "Андрогін",
  "Демібой",
  "Демігьорл",
  "Гендерно-нейтральний",
  "Маскулінний",
  "Фемінний",
  "Невизначений",
  "Бойовий гелікоптер 🚁",
  "Пилосос Dyson 🌀",
  "Капітан міжгалактичного флоту 🌌",
  "Апоргендер",
  "Нейрогендер",
  "Трансмаскулінний",
  "Трансфемінний",
  "Ксеногендер",
  "Гендерзірка 🌟",
  "Робот-гуманоїд 🤖",
  "Гібридний велосипед 🚴‍♂️",
  "Печиво з шоколадом 🍪",
]
lychko_response = "Личко, іді нахуй 🖕"
description = "Ласкаво просимо в 21 століття"
img_url = "https://www.aspistrategist.org.au/wp-content/uploads/2023/02/japanapache030223.jpg"

[zrada]
id = "05"
title = "Зрада чи перемога?"
responses = [
  "Це повна зрада!",
  "Невже перемога? Перемога буде, люди!",
  "Боротьба триває!",
  "Ганебна зрада!",
  "Перемога наша!",
  "Зрада, зрада, зрада!",
  "Перемога наша, браття!",
  "Зрада, руки опускаються...",
  "Пес Патрон, Пес Патрон, таких нам треба батальйон!",
]
description = "Дізнайтеся, чи на вас сьогодні чекає перемога чи зрада"
img_url = "https://mil.co.ua/wp-content/uploads/2023/06/27_main_9_500x317.jpg"
