[phases.setup]
aptPkgs = ['libpq-dev', 'pkg-config']

[phases.build]
cmds = ["cd /app && cargo build --release"]

[phases.runtime]
cmds = ["ls -l /app/target/release", "ls -l /", "ls -l /app", "ls -l /bin"]
aptPkgs = ['libpq5', 'libssl3']
