[phases.setup]
aptPkgs = [
  'libpq-dev',
  'pkg-config',
  'build-essential',
  'clang',
  'musl-tools',
  'make',
  'perl',
]

[phases.build]
cmds = [
  "export OPENSSL_STATIC=1",
  "export OPENSSL_VENDOR=1",
  "cargo build --release --target x86_64-unknown-linux-musl",
  "mkdir -p /app/bin",
  "cp target/x86_64-unknown-linux-musl/release/evil_lumios /app/bin/evil_lumios",
]

[phases.runtime]
aptPkgs = ['libpq5', 'libssl3']
