[phases.setup]
aptPkgs = ['libpq-dev', 'pkg-config']

[phases.build]
cmds = [
  "cargo build --release",
  "mkdir -p /app/bin",
  "cp target/release/evil_lumios /app/bin/evil_lumios",
]

[phases.runtime]
aptPkgs = ['libpq5', 'libssl3']
