//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod chats;
pub mod gambles;
pub mod queue_users;
pub mod queues;
pub mod timetable_entries;
pub mod timetables;
pub mod user_stats;
pub mod users;
