//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::chats::Entity as Chats;
pub use super::gambles::Entity as Gambles;
pub use super::queue_users::Entity as QueueUsers;
pub use super::queues::Entity as Queues;
pub use super::timetable_entries::Entity as TimetableEntries;
pub use super::timetables::Entity as Timetables;
pub use super::user_stats::Entity as UserStats;
pub use super::users::Entity as Users;
