//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "timetables")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub chat_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatId",
        to = "super::chats::Column::ChatId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Chats,
    #[sea_orm(has_many = "super::timetable_entries::Entity")]
    TimetableEntries,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::timetable_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimetableEntries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
